CREATE DATABASE IF NOT EXISTS proyectomanejo
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE proyectomanejo;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- --------------------
-- Catálogos base
-- --------------------

-- 1. Tablas de Catálogo y Referencia (Raíz)
CREATE TABLE IF NOT EXISTS TIPOS_CARRERA (
  ID_CARRERA TINYINT PRIMARY KEY AUTO_INCREMENT,
  NOMBRE_CARRERA VARCHAR(80) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ROLES (
  ID_ROL INT PRIMARY KEY AUTO_INCREMENT,
  NOM_ROL VARCHAR(100) NOT NULL,
  DES_ROL TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TIPOS_EVENTO (
  ID_TIPO_EVE INT PRIMARY KEY AUTO_INCREMENT,
  NOM_TIPO_EVE VARCHAR(100) UNIQUE NOT NULL,
  DES_TIPO_EVE TEXT,
  IMG_TIPO_EVE VARCHAR(255),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ************************************
-- ** ¡TABLA REQUISITOS MOVIDA AQUÍ! **
-- ************************************
-- Opción 1: Crear tabla desde cero (si quieres recrearla)
CREATE TABLE IF NOT EXISTS REQUISITOS (
  ID_REQ INT PRIMARY KEY AUTO_INCREMENT,
  NOM_REQ VARCHAR(120) UNIQUE NOT NULL,
  DES_REQ TEXT,
  TIPO ENUM('NUMERICO', 'DOCUMENTO', 'TEXTO_CORTO') NOT NULL,
  VALOR_MINIMO DECIMAL(12,2),        -- solo aplica para NUMERICO
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Opción 2: Modificar tabla existente
ALTER TABLE REQUISITOS
  DROP COLUMN VALOR_MAXIMO,
  DROP COLUMN MIME_PERMITIDOS,
  DROP COLUMN TAM_MAX_MB,
  DROP COLUMN VALOR_BOOLEANO,
  MODIFY COLUMN TIPO ENUM('NUMERICO', 'DOCUMENTO', 'TEXTO_CORTO') NOT NULL;

-- ************************************

-- 2. Tablas que dependen de Catálogo (USUARIOS depende de ROLES y TIPOS_CARRERA)
CREATE TABLE IF NOT EXISTS USUARIOS (
  CED_USU VARCHAR(10) PRIMARY KEY,
  NOM_PRI_USU VARCHAR(20) NOT NULL,
  NOM_SEG_USU VARCHAR(20),
  APE_PRI_USU VARCHAR(20) NOT NULL,
  APE_SEG_USU VARCHAR(20),
  COR_USU VARCHAR(100) NOT NULL UNIQUE,
  PAS_USU VARCHAR(8) NOT NULL,
  TEL_USU VARCHAR(10),
  DIR_USU VARCHAR(50),
  FEC_NAC_USU DATE,
  ID_ROL_USU INT,
  ID_CARRERA_USU TINYINT,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
  CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_USU_ROL      FOREIGN KEY (ID_ROL_USU)       REFERENCES ROLES(ID_ROL),
  CONSTRAINT FK_USU_CARRERA FOREIGN KEY (ID_CARRERA_USU) REFERENCES TIPOS_CARRERA(ID_CARRERA),
  INDEX idx_usuarios_rol (ID_ROL_USU),
  INDEX idx_usuarios_carrera (ID_CARRERA_USU)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Tablas de Relación Intermedia
-- (Ahora TIPOS_EVENTO_REQUISITOS se crea después de REQUISITOS)
CREATE TABLE IF NOT EXISTS TIPOS_EVENTO_REQUISITOS (
  ID_TIPO_EVE INT NOT NULL,
  ID_REQ INT NOT NULL,
  PRIMARY KEY (ID_TIPO_EVE, ID_REQ),
  CONSTRAINT FK_TIPOEVE_REQ_TIPO FOREIGN KEY (ID_TIPO_EVE) REFERENCES TIPOS_EVENTO(ID_TIPO_EVE) ON DELETE CASCADE,
  CONSTRAINT FK_TIPOEVE_REQ_REQ  FOREIGN KEY (ID_REQ)     REFERENCES REQUISITOS(ID_REQ) ON DELETE CASCADE,
  INDEX idx_tipo_req (ID_TIPO_EVE, ID_REQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Tablas de Entidades Principales (EVENTOS_CURSOS)
CREATE TABLE IF NOT EXISTS EVENTOS_CURSOS (
  ID_EVE_CUR INT PRIMARY KEY AUTO_INCREMENT,
  TIT_EVE_CUR VARCHAR(150) NOT NULL,
  DES_EVE_CUR TEXT,
  INSCRIPCION_DESDE DATE,
  INSCRIPCION_HASTA DATE,
  FEC_INI_EVE_CUR DATE NOT NULL,
  FEC_FIN_EVE_CUR DATE NOT NULL,
  MOD_EVE_CUR ENUM('Gratis', 'Pagado') NOT NULL DEFAULT 'Gratis',
  COS_EVE_CUR DECIMAL(10,2) NOT NULL DEFAULT 0,
  LUGAR VARCHAR(100),
  UBICACION_DETALLE VARCHAR(100),
  CAPACIDAD_MAXIMA INT NOT NULL DEFAULT 0,
  CUPOS_DISPONIBLES INT NOT NULL DEFAULT 0,
  HORAS_TOTALES INT,
  ID_TIPO_EVE INT NOT NULL,
  RESPONSABLE_CED VARCHAR(10) NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
  CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_EVENTO_TIPO         FOREIGN KEY (ID_TIPO_EVE)  REFERENCES TIPOS_EVENTO(ID_TIPO_EVE) ON DELETE RESTRICT,
  CONSTRAINT FK_EVENTO_RESPONSABLE FOREIGN KEY (RESPONSABLE_CED) REFERENCES USUARIOS(CED_USU) ON DELETE SET NULL,
  INDEX idx_eventos_fechas (FEC_INI_EVE_CUR, FEC_FIN_EVE_CUR),
  INDEX idx_inscripcion_fechas (INSCRIPCION_DESDE, INSCRIPCION_HASTA),
  INDEX idx_cupos (CUPOS_DISPONIBLES),
  INDEX idx_evento_tipo (ID_TIPO_EVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 5. Tablas de Relaciones Secundarias (Dependen de EVENTOS_CURSOS)
CREATE TABLE IF NOT EXISTS EVENTOS_CARRERAS (
  ID_EVE_CUR INT NOT NULL,
  ID_CARRERA TINYINT NOT NULL,
  PRIMARY KEY (ID_EVE_CUR, ID_CARRERA),
  CONSTRAINT FK_EVECAR_EVE    FOREIGN KEY (ID_EVE_CUR)  REFERENCES EVENTOS_CURSOS(ID_EVE_CUR) ON DELETE CASCADE,
  CONSTRAINT FK_EVECAR_CARRERA FOREIGN KEY (ID_CARRERA) REFERENCES TIPOS_CARRERA(ID_CARRERA) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PERSONAL_EVENTO (
  ID_EVE_CUR INT NOT NULL,
  CED_USU VARCHAR(10) NOT NULL,
  ROL_EVENTO ENUM('PONENTE','ASISTENTE') NOT NULL,
  ES_RESPONSABLE TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID_EVE_CUR, CED_USU, ROL_EVENTO),
  CONSTRAINT FK_PERS_EVE FOREIGN KEY (ID_EVE_CUR) REFERENCES EVENTOS_CURSOS(ID_EVE_CUR) ON DELETE CASCADE,
  CONSTRAINT FK_PERS_USU FOREIGN KEY (CED_USU)      REFERENCES USUARIOS(CED_USU)          ON DELETE CASCADE,
  INDEX idx_responsable (ID_EVE_CUR, ES_RESPONSABLE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EVENTOS_FAVORITOS (
  ID_EVE_CUR INT NOT NULL,
  FECHA_MARCADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ( ID_EVE_CUR),
  CONSTRAINT FK_FAV_EVE FOREIGN KEY (ID_EVE_CUR) REFERENCES EVENTOS_CURSOS(ID_EVE_CUR) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EVENTOS_REQUISITOS (
  ID_EVE_CUR INT NOT NULL,
  ID_REQ INT NOT NULL,
  OBLIGATORIO TINYINT(1) NOT NULL DEFAULT 1,
  ORDEN TINYINT DEFAULT 0,
  VALOR_MINIMO_APROBATORIO DECIMAL(12,2),
  INSTRUCCIONES_ESPECIFICAS TEXT,
  PRIMARY KEY (ID_EVE_CUR, ID_REQ),
  CONSTRAINT FK_EVEREQ_EVE FOREIGN KEY (ID_EVE_CUR) REFERENCES EVENTOS_CURSOS(ID_EVE_CUR) ON DELETE CASCADE,
  CONSTRAINT FK_EVEREQ_REQ FOREIGN KEY (ID_REQ)      REFERENCES REQUISITOS(ID_REQ)         ON DELETE CASCADE,
  INDEX idx_orden (ID_EVE_CUR, ORDEN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Tablas de Transacciones (INSCRIPCIONES)
CREATE TABLE IF NOT EXISTS INSCRIPCIONES (
  ID_INS INT PRIMARY KEY AUTO_INCREMENT,
  CED_USU VARCHAR(10) NOT NULL,
  ID_EVE_CUR INT NOT NULL,
  FEC_INI_INS DATE NOT NULL,
  FEC_CIE_INS DATE NOT NULL,
  ESTADO_INS ENUM('Preinscrito', 'Inscrito', 'En lista de espera', 'Cancelado', 'Completado') NOT NULL DEFAULT 'Preinscrito',
  EST_PAG_INS ENUM('Pendiente', 'Pagado') NOT NULL DEFAULT 'Pendiente',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_inscripcion (CED_USU, ID_EVE_CUR),
  CONSTRAINT FK_INS_USU FOREIGN KEY (CED_USU)    REFERENCES USUARIOS(CED_USU),
  CONSTRAINT FK_INS_EVE FOREIGN KEY (ID_EVE_CUR) REFERENCES EVENTOS_CURSOS(ID_EVE_CUR),
  INDEX idx_inscripcion_estado (ESTADO_INS),
  INDEX idx_inscripcion_pago (EST_PAG_INS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. Tablas de Detalles de Transacciones (PAGOS, EVIDENCIAS, LISTA_ESPERA)
CREATE TABLE IF NOT EXISTS LISTA_ESPERA (
  ID_LISTA_ESPERA INT PRIMARY KEY AUTO_INCREMENT,
  ID_EVE_CUR INT NOT NULL,
  CED_USU VARCHAR(10) NOT NULL,
  POSICION INT NOT NULL,
  FECHA_SOLICITUD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ESTADO ENUM('Activa', 'Atendida', 'Cancelada') NOT NULL DEFAULT 'Activa',
  UNIQUE KEY unique_lista_espera (ID_EVE_CUR, CED_USU),
  CONSTRAINT FK_WAIT_EVE FOREIGN KEY (ID_EVE_CUR) REFERENCES EVENTOS_CURSOS(ID_EVE_CUR) ON DELETE CASCADE,
  CONSTRAINT FK_WAIT_USU FOREIGN KEY (CED_USU)    REFERENCES USUARIOS(CED_USU)          ON DELETE CASCADE,
  INDEX idx_posicion (ID_EVE_CUR, POSICION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PAGOS (
  ID_PAG INT PRIMARY KEY AUTO_INCREMENT,
  ID_INS INT NOT NULL,
  FEC_PAG TIMESTAMP NOT NULL,
  MON_PAG DECIMAL(10,2) NOT NULL,
  MET_PAG VARCHAR(50) NOT NULL DEFAULT 'Efectivo',
  URL_COMPROBANTE TEXT NOT NULL,
  ESTADO_VALIDACION ENUM('Pendiente', 'Aprobado', 'Rechazado') NOT NULL DEFAULT 'Pendiente',
  REVISADO_POR VARCHAR(10),
  REVISADO_EN TIMESTAMP NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_PAG_INS FOREIGN KEY (ID_INS)      REFERENCES INSCRIPCIONES(ID_INS) ON DELETE CASCADE,
  CONSTRAINT FK_PAG_REV FOREIGN KEY (REVISADO_POR) REFERENCES USUARIOS(CED_USU)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EVIDENCIAS (
  ID_EVIDENCIA INT PRIMARY KEY AUTO_INCREMENT,
  ID_INS INT NOT NULL,
  ID_REQ INT NOT NULL,
  VALOR_NUMERICO DECIMAL(12,2),
  VALOR_TEXTO VARCHAR(500),
  VALOR_BOOLEANO TINYINT(1),
  NOMBRE_ARCHIVO VARCHAR(255),
  URL_ARCHIVO TEXT,
  TIPO_MIME VARCHAR(100),
  TAMANIO_BYTES INT,
  ESTADO_VALIDACION ENUM('Pendiente', 'Aprobado', 'Rechazado') NOT NULL DEFAULT 'Pendiente',
  OBSERVACION TEXT,
  FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  REGISTRADO_POR VARCHAR(10),
  REVISADO_POR VARCHAR(10),
  REVISADO_EN TIMESTAMP NULL,
  UNIQUE KEY unique_evidencia (ID_INS, ID_REQ),
  CONSTRAINT FK_EVID_INS FOREIGN KEY (ID_INS)          REFERENCES INSCRIPCIONES(ID_INS) ON DELETE CASCADE,
  CONSTRAINT FK_EVID_REQ FOREIGN KEY (ID_REQ)          REFERENCES REQUISITOS(ID_REQ)    ON DELETE CASCADE,
  CONSTRAINT FK_EVID_REG FOREIGN KEY (REGISTRADO_POR) REFERENCES USUARIOS(CED_USU),
  CONSTRAINT FK_EVID_REV FOREIGN KEY (REVISADO_POR)    REFERENCES USUARIOS(CED_USU),
  INDEX idx_evidencia_estado (ESTADO_VALIDACION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;